### ISSUE TITLE
Better error handling? Crashes when an attribute is not present

### ISSUE THREAD

**Issue by gingerbeardman** [source-foundry/font-line#14]
Try getting a `font-line report` on these fonts:

https://github.com/schmiddim/Kobo-Touch-Firmware--1.9.17/tree/master/usr/local/Trolltech/QtEmbedded-4.6.2-arm/lib/fonts

I get:

```MacBookPro-Matt:fonts matt$ font-line report Amasis/*
Traceback (most recent call last):
  File "/usr/local/bin/font-line", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/fontline/app.py", line 54, in main
    stdout(get_font_report(fontpath))
  File "/Library/Python/2.7/site-packages/fontline/commands.py", line 22, in get_font_report
    os2_x_height = tt['OS/2'].sxHeight
AttributeError: 'table_O_S_2f_2' object has no attribute 'sxHeight'
```
Maybe this scenario could be dealt with better?

Maybe there could be a command line option to silence error output? 

Until then I will have to hack around it in the shell script I am working on (or not use those fonts).

ps: Thanks for this tool! It surprised me how difficult it is to get the metrics data on the command line.

**Comment by chrissimpkins** [comment]
Absolutely and apologies.  I wasn't aware that this was an optional value in the OpenType tables.  Any idea what compiler is being used to build those fonts and where source is located (if available)?

**Comment by chrissimpkins** [comment]
This can be a quick fix so don't go to too much immediate trouble to create new scripts.   Just need a bit more info to troubleshoot it.

**Comment by gingerbeardman** [comment]
I honestly have no idea about the fonts I just found them to use on my eBook reader. I've seen this sxHeight issue in fonts from eBook readers (I have some others with the same issue that came pre-installed on my Sony Reader). 

No idea why they would exclude it?

**Comment by chrissimpkins** [comment]
OK thanks.  Will take a look and catch those exceptions so that you get reports without the data when it is not present.

**Comment by chrissimpkins** [comment]
I can replicate this on the Amasis-Bold.ttf file that you linked. 

Here is the OS/2 table from that font:

![ot-table](https://user-images.githubusercontent.com/4249591/33226753-a2754ca6-d162-11e7-8546-5b2afc51597f.png)

Definitely no sxHeight or sCapHeight records in the tables.

**Comment by chrissimpkins** [comment]
Fix catches `AttributeError` on both CapHeight and xHeight values:

![font_line-fix](https://user-images.githubusercontent.com/4249591/33226828-f8cbd740-d163-11e7-94a9-5f076cb93738.png)

Reports missing values and exits with remainder of available values gracefully.

**Comment by chrissimpkins** [comment]
fix pushed in https://github.com/source-foundry/font-line/commit/123fbb778e710a110945b472e23745900c677d9e

**Comment by chrissimpkins** [comment]
I will need to find an open source / redistributable font that I can use to add unit tests for this issue.  That font can't be added to our test fonts here.

**Comment by chrissimpkins** [comment]
Fix available on PyPI as v0.7.1.  @gingerbeardman you can upgrade to the fixed version with:

```
$ pip install --upgrade font-line
```

Thank you very much for taking the time to report this!  Feel free to reopen if you continue to experience problems.

**Comment by gingerbeardman** [comment]
Beauty! Thanks so much for fixing it so quickly. Overnight in my timezone!

I'll let you know if I come across such a font with a redistributable licence, or a way to generate a font without these records.

**Comment by gingerbeardman** [comment]
Also, what app did you use to generate the font table screenshot?

**Comment by chrissimpkins** [comment]
@gingerbeardman 

> Beauty! Thanks so much for fixing it so quickly.

No problem at all.  Appreciate the feedback for the fix.

> I'll let you know if I come across such a font with a redistributable licence, or a way to generate a font without these records.

👍 

> Also, what app did you use to generate the font table screenshot?

Dutch Type Library OTMaster Light.  You can find download links on the right sidebar of this page: 

http://www.fontmaster.nl/
