### ISSUE TITLE
shebang issue

### ISSUE THREAD

**Issue by gingerbeardman** [source-foundry/font-line#17]
had to reinstall this recently and had an issue where python was not found

`-bash: /usr/local/bin/font-line: /usr/local/opt/python/bin/python2.7: bad interpreter: No such file or directory
`

it's recommended to use this instead

`
#!/usr/bin/env python
`

**Comment by gingerbeardman** [comment]
uninstalled and reinstalled and it uses the recommended env approach

sorry for false alarm

**Comment by chrissimpkins** [comment]
@gingerbeardman Might have been your PATH settings linked through `env`.  I don't believe that we have ever used the first path as the shebang line in the source files.

**Comment by gingerbeardman** [comment]
very odd! cheers

**Comment by chrissimpkins** [comment]
@gingerbeardman Cheers back at ya! :)
