### ISSUE TITLE
Font weight changed after changing the interline spacing

### ISSUE THREAD

**Issue by psycha0s** [source-foundry/font-line#4]
After changing the interline spacing bold font looks too bold.

Before:
![2](https://cloud.githubusercontent.com/assets/8014057/14144517/ad2b948a-f698-11e5-989a-e0d912675613.png)

After:
![1](https://cloud.githubusercontent.com/assets/8014057/14144508/a718e32c-f698-11e5-8a56-bcafe263131a.png)

Though I'm unsure whether this is a font-line issue because I got very similar results after increasing the interline spacing manually with fontforge.

**Comment by chrissimpkins** [comment]
What editor on Linux?

**Comment by psycha0s** [comment]
It's kate from KDE.

**Comment by chrissimpkins** [comment]
mind printing out the metrics report with the command:

```
$ font-line report [fontpath]
```

Addendum: for pre-modification and post-modification files...

**Comment by psycha0s** [comment]
Sure:

```
$ font-line report Hack-Bold-linegap50.ttf

=== Hack-Bold-linegap50.ttf ===
b'Version 2.019; ttfautohint (v1.4.1) -l 4 -r 80 -G 350 -x 0 -H 260 -D latn -f latn -m "Hack-Bold-TA.txt" -w G -W -t -X ""'
SHA1: fc1fefee0e52f0962104ae81efab57e682aff75d

--- Metrics ---
[head] Units per Em:    2048
[head] yMax:            1980
[head] yMin:            -807
[OS/2] TypoAscender:    1556
[OS/2] TypoDescender:   -492
[OS/2] WinAscent:       2068
[OS/2] WinDescent:      1004
[hhea] Ascent:          2068
[hhea] Descent:         -1004

[hhea] LineGap:         0
[OS/2] TypoLineGap:     1024

--- Height Calculations by Table Values ---
[OS/2] TypoAscender to TypoDescender:   2048
[OS/2] WinAscent to WinDescent:         3072
[hhea] Ascent to Descent:               3072

--- Delta Values ---
WinAscent to TypoAscender:      512
Ascent to TypoAscender:         512
WinDescent to TypoDescender:    512
Descent to TypoDescender:       512

--- Ratios ---
(Typo Asc + Desc + Linegap) / UPM:      1.5
(winAsc + winDesc) / UPM:               1.5
(hhea Asc + Desc) / UPM:                1.5

```

**Comment by psycha0s** [comment]
Yeah, it seems like a KDE issue. Sublime text shows my modified font correctly.

**Comment by chrissimpkins** [comment]
Might be worth an issue report on the Kate tracker.

Are you happy with the line spacing adjustments?  It looks like it does render with expanded line spacing in your screenshot.

**Comment by psycha0s** [comment]
Yes, amazing that it's possible to do a flexible adjustment from the command line now. Great work, @chrissimpkins! Thanks for this tool.

**Comment by chrissimpkins** [comment]
@phantom-code Great to hear!  Mind closing if this is addressed?

**Comment by psycha0s** [comment]
I'm still unsure if we can think about this issue that it's addressed, but I close it for now.

**Comment by chrissimpkins** [comment]
If you come across additional information feel free to reopen and post it!

**Comment by psycha0s** [comment]
It seems that QtCreator has the same issue.

before:
![2](https://cloud.githubusercontent.com/assets/8014057/14586662/007b9392-04a9-11e6-8d58-9dd11b652ce3.png)

after:
![1](https://cloud.githubusercontent.com/assets/8014057/14586663/0553c1b4-04a9-11e6-961e-da575ae1864d.png)

**Comment by chrissimpkins** [comment]
mind trying with a couple of other fonts to see if you find the same problem? I don't know if this is the change or the way that we have the line spacing set that is leading to problems.

**Comment by psycha0s** [comment]
Sure, I'll try it tonight.

**Comment by chrissimpkins** [comment]
Any updates here?

**Comment by psycha0s** [comment]
Oh! I'm sorry, I thought my answer was sent. I modified the "LiberationMono" font and it looks as it should in QtCreator:

![screenshot](https://cloud.githubusercontent.com/assets/8014057/15213582/dc5ef308-1850-11e6-8c97-acada8651d6f.png)

**Comment by chrissimpkins** [comment]
Thank you! I will see if I can find any documentation on the renderer used in QtCreator.  @jorgheymans is currently working on a command line tool to emulate text editor renders with the Java rendering approach and we have plans to do this across more renderer types so that we can move this testing out of the editors.  Will see if this editor's renderer is amenable to this approach.
