### ISSUE TITLE
Report data modification and writing back to fontfile! 

### ISSUE THREAD

**Issue by mistu01** [source-foundry/font-line#69]
First of all thanks for the great tool. Very handy. 
I am just asking/suggesting a feature improvement. In the next update if it is possible please add an option to write back the modified fontreport.txt data to the fontfile. That would be very fancy feature to have! 
Thank You.

**Comment by chrissimpkins** [comment]
Thanks for the note! To clarify your request here, you would like the report command output to be available in a table in the binary? Where / how would it be ideal to access it?

My initial concern about this is that a tool could change the metrics data in the font and not update the information that is recorded by font-line in the binary. How should we approach that?

**Comment by mistu01** [comment]
@chrissimpkins i am not very familiar in this field, also not very techy to with all the terminology. so you have to pardon me for my limited knowledge. 

I want to change the `Metrics` table values which are generated in the text file` (ie, [head] yMax:, [head] yMin:, [OS/2] TypoAscender:... and other values)` to gain the line-gap according to my personal taste, where I know the default way to change is to use the percentage command. 

I also not that good or able to tell you how can we achieve that. My thoughts are this: We generate the Metrics table in a text file and will it be possible to write back the modified values to the font anyhow? something like `font-line font-report.txt > font.ttf` may be? 

i can do it with any font-editor app/software (fontforge or anything of such sort) but as command line utilities are always faster in working with, also if I ever in need of editing in bulk amount it would be a perfect choice.

**Comment by chrissimpkins** [comment]
Ah, I see. Are you familiar with Python? This should be reasonably straightforward using the fonttools library and your config file format of choice.

**Comment by mistu01** [comment]
Thank you very much for the information. 
Yes I am a little familiar with Python and fonttools. I sometimes use fonttool's TTX but not very advanced user. Can you link me to some tutorial or article from where people like me (with limited knowledge) can learn about what I am trying to achieve here?

**Comment by chrissimpkins** [comment]
No problem.  The [fontTools.ttLib.TTFont](https://fonttools.readthedocs.io/en/latest/ttLib/ttFont.html) documentation will be a good place to start.  TTFont is a font object that is instantiated from a binary file path.  It provides access to all of the OpenType tables that you will need to edit and is the data structure that is used in font-line for read/write access to the metrics data.  

Have a look at https://github.com/source-foundry/font-line/blob/fad1442f1746ebffff19fbf48cefaf501fc2b17a/lib/fontline/metrics.py#L17-L63 for details on how to get at the metrics data in each of the relevant OT tables.  In that block of font-line source, `tt` is the `TTFont` object.  What you will want to do is edit those data with the desired values and then [`save`](https://fonttools.readthedocs.io/en/latest/ttLib/ttFont.html#fontTools.ttLib.ttFont.TTFont.save) the font to disk. `save` takes a file path and allows you to either save in place or on a different path.  I think that the only missing piece will be to decide how you want to configure the data.  JSON is supported in the Python stdlib.  There are 3rd party packages on PyPI for toml, yaml, etc.  Those should be the pieces to get to where you want to go!

Let me know if you run into any issues and if you come up with something that others can use!

**Comment by mistu01** [comment]
Thanks for taking all this time to help me. I will try to get something out of it. Thank you again.
