### ISSUE TITLE
Capital height and X height in Metrics Report. Feasible?

### ISSUE THREAD

**Issue by ollicle** [source-foundry/font-line#9]
Would it be feasible for the report generated by font-line to include values for:

- Capital Height
- X Height

I am interested in this functionality as a command line friendly alternative to using <http://fontforge.github.io> as suggested by [this informative article](http://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align#lets-talk-about-font-size-first) to discover metrics for a given font.

**Comment by chrissimpkins** [comment]
Will have a look into this over the weekend and be back in touch about it Oliver.

**Comment by chrissimpkins** [comment]
Yes, we can get at both cap height:

https://www.microsoft.com/typography/otspec/os2.htm#ch

and x height:

https://www.microsoft.com/typography/otspec/os2.htm#xh

data in the OpenType tables.  Want to have a read through those specification docs and confirm that this is the information that you need?  If so, we can create a new release with this information.  If you program in Python, you are more than welcome to tackle this and pull request it in.  If not, I'd be happy to add it.

Let me know how you'd like to approach it.  One way or the other we will get the data that you need.

**Comment by chrissimpkins** [comment]
Also, please let me know if it is more helpful to have a tool that helps with web font layout issues.  Are you performing calculations with these metrics and do you need something that automates that?  If so, that can be automated in a different tool that is web specific.

**Comment by ollicle** [comment]
@chrissimpkins appears the values you have linked to (`sCapHeight` and `sxHeight`) are exactly what I had in mind.

You surmise correctly that I am working to solve a web typography problem. Specifically I am attempting to calculate the relative space between the top of the letters (for a given font at a specified font-size and line-height) and the top of it’s containing element.

Using this value to negate this space with CSS will permit the vertical space above the text to be determined by padding on the containing element rather than a complicated combination of both.

Early experiments, although not as accurate as I would like, are looking promising. My hope is a tool like font-line and some CSS pre-processor calculations will make it simple enough to fit into a regular workflow (fonts permitting). If you know of more specific tools I’d be _very interested_ to see them.

Alas my Python is sub-beginner level, but it is great that you gave me the opportunity to contribute more directly, thank-you.

**Comment by chrissimpkins** [comment]
Confirming that you will have access to the ttf or otf fonts?  Don't have a direct way to access woff / woff2 tables for these data with this application.

**Comment by ollicle** [comment]
Yes, it would be unusual, at least in my circumstance, to have only the woff version. Thanks for your forethought.

**Comment by chrissimpkins** [comment]
👍 On the to do list!  Will try to get to it this week.  Shouldn't be a major effort. 

Also, shameless plug in case it is helpful.  Woffle uses the same ttf/otf >> woff + woff2 build process that we use in Hack if you are on OS X and want a simple DnD approach to build your web fonts.

https://github.com/source-foundry/Woffle

**Comment by chrissimpkins** [comment]
Updated with these new metrics and released as v0.7.0. 

You can upgrade a previous install with:

```
$ pip install --upgrade font-line
```

The command functions as before:

```
$ font-line report [font path 1] <font path ...>
```

Please let me know if you come across any problems.  Thanks for the suggestion!

**Comment by chrissimpkins** [comment]
@ollicle Sorry, should have pointed out, here is how the new report appears:

```
=== Hack-Regular.ttf ===
Version 3.001; 379b3ad6d-dev
SHA1: 20d02edca75f2d23787e80161a64418598c850de

--- Metrics ---
[head] Units per Em: 	2048
[head] yMax: 		2027
[head] yMin: 		-605
[OS/2] CapHeight: 	1493
[OS/2] xHeight: 	1120
[OS/2] TypoAscender: 	1556
[OS/2] TypoDescender: 	-492
[OS/2] WinAscent: 	1901
[OS/2] WinDescent: 	483
[hhea] Ascent: 		1901
[hhea] Descent: 	-483

[hhea] LineGap: 	0
[OS/2] TypoLineGap: 	410

--- Height Calculations by Table Values ---
[OS/2] TypoAscender to TypoDescender: 	2048
[OS/2] WinAscent to WinDescent: 	2384
[hhea] Ascent to Descent: 		2384

--- Delta Values ---
WinAscent to TypoAscender: 	345
Ascent to TypoAscender: 	345
WinDescent to TypoDescender: 	-9
Descent to TypoDescender: 	-9

--- Ratios ---
(Typo Asc + Desc + Linegap) / UPM: 	1.2
(winAsc + winDesc) / UPM: 		1.16
(hhea Asc + Desc) / UPM: 		1.16
```

Cap height and xHeight are under the Metrics header.  Enjoy!

**Comment by ollicle** [comment]
I hope to try this out later this week. Thank-you!

**Comment by chrissimpkins** [comment]
Enjoy!
